### ISSUE TITLE
MISSING ITEMS  

### ISSUE THREAD

**Issue by markbucko12341** [pushkart2/qb-restaurantjob#4]
missing items for qbcore > sheared.lua 
you only listed one  .. without  the others added you cant make a pizza

**Comment by Kxcp3r** [comment]
> missing items for qbcore > sheared.lua you only listed one .. without the others added you cant make a pizza

Hello, Whats your discord so I may contact you for support

**Comment by pushkart2** [comment]
The script is just made to give the overall logic of how it works. The only thing you have to do is add items in shared.lua and config.
I wont be adding items in shared.lua
